<%@ page language="java" contentType="text/html; charset=EUC-KR"
    pageEncoding="EUC-KR"%>
[    
{
  "empno":7788,
  "sal":8000,
  "ename":"smith"
},
{
  "empno":7789,
  "sal":5000,
  "ename":"allen"
},
{
  "empno":7738,
  "sal":2000,
  "ename":"king"
}
]